version: "3"

services:
  vsftpd:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    restart: always
    environment:
      FTP_USER: admin
      FTP_PASS: admin
    ports:
      - 0.0.0.0:2020:20
      - 0.0.0.0:2021:21
      - 21100-21110:21100-21110
    volumes:
      - ./home:/home/vsftpd
      - ./logs:/var/log/vsftpd
